### ISSUE TITLE
The circle around a selected point renders behind other points

### ISSUE THREAD

**Issue by jcommelin** [jcommelin/superficie-algebriche#16]
The black circle is drawn too early, before the other grey dots are drawn.
![2015-01-16-152638_23x28_scrot](https://cloud.githubusercontent.com/assets/5636705/5777517/7dd54352-9d93-11e4-8573-e86d9f7c5971.png)

**Comment by pbelmans** [comment]
I was aware of this, now that someone else noticed I guess I should fix this. It's easy though, I already am reordering the nodes anyway. Remark that the black circle is not "drawn", but is a border on an actual circle (the gray dot). SVG doesn't have z-index, which is why one has to annoyingly reorder nodes all the time.

**Comment by jcommelin** [comment]
Ouch. I hoped z-index could fix this. Well, we can work it out anyway. Alternatively, you just redraw the gray dot + its black circle.
